export const REGISTER_DATA = 'REGISTER_DATA';
export const REGISTER_RANDOM_DATA = 'REGISTER_RANDOM_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const CHECK_INTERNET = 'CHECK_INTERNET';
export const SET_APP_STATE = 'SET_APP_STATE';
